package llvm

import (
	"fmt"
	"strings"
)

// Generator holds mutable state while walking the AST and emitting IR.
// Create one per compilation unit (one per Program) ? it is NOT safe to
// reuse across multiple Generate() calls, and NOT safe for concurrent use.
type Generator struct {
	sb strings.Builder

	// SSA register counter. LLVM IR is in SSA form ? every intermediate
	// value needs a unique name. We use %tN and increment per use.
	tmpCount int

	// Label counter for if/else branch blocks.
	labelCount int

	// scope maps a Whale variable name -> the LLVM pointer (%name) that
	// holds it. We use the standard "alloca every local, let mem2reg
	// optimize it away" pattern ? this is exactly what clang itself does
	// for unoptimized -O0 IR. It's the simplest correct way to handle
	// variables and reassignment without hand-rolling SSA phi nodes.
	scope map[string]scopedVar

	// stringConstants collects string literals we need to emit as global
	// constants at module scope (LLVM doesn't allow string literals inline
	// in instructions ? they must be globals).
	stringConstants []stringConst

	// declaredExterns tracks which libc functions we've already forward-
	// declared (e.g. printf), so we don't emit duplicate declares.
	declaredExterns map[string]bool

	// structs tracks user-defined struct declarations to emit types and
	// map field names to indices.
	structs map[string]*StructDecl
	enums   map[string]*EnumDecl

	// trampolines collects generated trampoline functions for spawn.
	trampolines strings.Builder
}

type scopedVar struct {
	llvmName string // e.g. "%x"
	ty       Type
}

type stringConst struct {
	globalName string // e.g. "@.str.0"
	value      string
	length     int // byte length including the null terminator
}

// NewGenerator creates a fresh codegen state.
func NewGenerator() *Generator {
	return &Generator{
		scope:           map[string]scopedVar{},
		declaredExterns: map[string]bool{},
		structs:         map[string]*StructDecl{},
		enums:           map[string]*EnumDecl{},
	}
}

// Generate walks the full Program AST and returns complete LLVM IR text
// for the module, ready to be written to a .ll file.
func (g *Generator) Generate(prog *Program) string {
	var body strings.Builder

	for _, s := range prog.Structs {
		g.structs[s.Name] = s
	}
	for _, e := range prog.Enums {
		g.enums[e.Name] = e
	}

	for _, fn := range prog.Functions {
		body.WriteString(g.genFunc(fn))
		body.WriteString("\n")
	}
	body.WriteString(g.trampolines.String())

	// Assemble the final module: header, extern declarations, string
	// constants, then the function bodies we generated above. We do it in
	// this order because LLVM IR requires globals/declares to appear
	// before (or anywhere in the module, but conventionally before) their
	// use for human readability, though LLVM itself doesn't strictly
	// require top-to-bottom ordering for module-level definitions.
	var out strings.Builder
	out.WriteString("; ============================================================\n")
	out.WriteString("; Generated by the Whale native codegen backend (Phase 7)\n")
	out.WriteString("; Do not hand-edit ? regenerate from source instead.\n")
	out.WriteString("; ============================================================\n\n")

	out.WriteString("%WhaleArray = type { i64, ptr }\n\n")

	// Struct definitions
	for _, s := range prog.Structs {
		out.WriteString(fmt.Sprintf("%%struct.%s = type { ", s.Name))
		for i, f := range s.Fields {
			if i > 0 {
				out.WriteString(", ")
			}
			out.WriteString(g.llvmType(f.Type))
		}
		out.WriteString(" }\n")
	}

	// Enum definitions
	for _, e := range prog.Enums {
		out.WriteString(fmt.Sprintf("%%enum.%s = type { i32", e.Name))
		for _, v := range e.Variants {
			if v.Type != "" {
				out.WriteString(", ")
				out.WriteString(g.llvmType(v.Type))
			}
		}
		out.WriteString(" }\n")
	}

	if len(prog.Structs) > 0 {
		out.WriteString("\n")
	}

	// Extern declarations (e.g. printf from libc, used by print(...)).
	for name := range g.declaredExterns {
		out.WriteString(externDecl(name))
		out.WriteString("\n")
	}
	if len(g.declaredExterns) > 0 {
		out.WriteString("\n")
	}

	// Global string constants collected while generating function bodies.
	for _, sc := range g.stringConstants {
		// NOTE: llvmEscapeString already produces LLVM's \XX hex-escape
		// format ? do NOT wrap it in fmt's %q (that applies Go string
		// escaping on top and corrupts the output).
		out.WriteString(fmt.Sprintf(
			"%s = private unnamed_addr constant [%d x i8] c\"%s\"\n",
			sc.globalName, sc.length, llvmEscapeString(sc.value),
		))
	}
	if len(g.stringConstants) > 0 {
		out.WriteString("\n")
	}

	out.WriteString(body.String())
	return out.String()
}

// ---------------------------------------------------------------------------
// Function codegen
// ---------------------------------------------------------------------------

func (g *Generator) genFunc(fn *FuncDecl) string {
	// Fresh per-function state: SSA temp counters and variable scope don't
	// leak across functions.
	g.tmpCount = 1
	g.labelCount = 1
	g.scope = map[string]scopedVar{}

	var out strings.Builder

	// signature
	paramStrs := make([]string, len(fn.Params))
	for i, p := range fn.Params {
		paramStrs[i] = fmt.Sprintf("%s %%%s.arg", g.llvmType(p.Type), p.Name)
	}
	out.WriteString(fmt.Sprintf("define %s @%s(%s) {\n",
		g.llvmType(fn.ReturnType), fn.Name, strings.Join(paramStrs, ", "),
	))
	out.WriteString("entry:\n")

	// allocate local copies of params (mem2reg will clean this up).
	for _, p := range fn.Params {
		reg := "%" + p.Name
		out.WriteString(fmt.Sprintf("  %s = alloca %s\n", reg, g.llvmType(p.Type)))
		out.WriteString(fmt.Sprintf("  store %s %%%s.arg, ptr %s\n", g.llvmType(p.Type), p.Name, reg))
		g.scope[p.Name] = scopedVar{llvmName: reg, ty: p.Type}
	}

	if fn.Name == "main" {
		out.WriteString("  %gc_stack_top = alloca i32\n")
		out.WriteString("  call void @whale_gc_init(ptr %gc_stack_top)\n")
		g.declaredExterns["whale_gc_init"] = true
	}

	// emit body
	bodyIR, terminated := g.genBlock(fn.Body)
	out.WriteString(bodyIR)

	// ensure every block terminates correctly
	if !terminated {
		if fn.ReturnType == TypeVoid {
			out.WriteString("  ret void\n")
		} else {
			// A real compiler would flag this as a "missing return" error
			// during type checking. Here, we just inject a zero value so
			// LLVM doesn't reject the IR.
			out.WriteString(fmt.Sprintf("  ret %s %s\n", g.llvmType(fn.ReturnType), zeroValue(fn.ReturnType)))
		}
	}
	out.WriteString("}\n")
	return out.String()
}

// genBlock emits IR for a slice of statements. Returns (IR, bool) where
// bool is true if the block ended with a terminating instruction (like
// return), meaning we shouldn't emit further code in this block.
func (g *Generator) genBlock(stmts []Stmt) (string, bool) {
	var out strings.Builder
	terminated := false

	for _, stmt := range stmts {
		if terminated {
			// any statements after a return are unreachable
			break
		}
		switch s := stmt.(type) {
		case *LetStmt:
			out.WriteString(g.genLet(s))
		case *ReturnStmt:
			out.WriteString(g.genReturn(s))
			terminated = true
		case *IfStmt:
			ir, term := g.genIf(s)
			out.WriteString(ir)
			terminated = term
		case *ExprStmt:
			ir, _, _ := g.genExpr(s.X, &out)
			out.WriteString(ir)
		case *WhileStmt:
			ir, term := g.genWhile(s)
			out.WriteString(ir)
			terminated = term
		case *AssignStmt:
			ir := g.genAssign(s)
			out.WriteString(ir)
		case *AssignIndexStmt:
			ir := g.genAssignIndex(s)
			out.WriteString(ir)
		case *SpawnStmt:
			ir := g.genSpawn(s)
			out.WriteString(ir)
		case *ChanSendStmt:
			ir := g.genChanSend(s)
			out.WriteString(ir)
		default:
			panic(fmt.Sprintf("codegen: unhandled statement type %T", stmt))
		}
	}
	return out.String(), terminated
}

func (g *Generator) genLet(s *LetStmt) string {
	var out strings.Builder
	valIR, valReg, valTy := g.genExpr(s.Value, &out)
	out.WriteString(valIR)

	reg := "%" + s.Name
	out.WriteString(fmt.Sprintf("  %s = alloca %s\n", reg, g.llvmType(s.Type)))
	out.WriteString(fmt.Sprintf("  store %s %s, ptr %s\n", g.llvmType(valTy), valReg, reg))

	g.scope[s.Name] = scopedVar{llvmName: reg, ty: s.Type}
	return out.String()
}

func (g *Generator) genAssign(s *AssignStmt) string {
	var out strings.Builder
	_, valReg, valTy := g.genExpr(s.Value, &out)
	
	v, ok := g.scope[s.Name]
	if !ok {
		panic(fmt.Sprintf("codegen: undefined variable %q in assignment", s.Name))
	}
	out.WriteString(fmt.Sprintf("  store %s %s, ptr %s\n", g.llvmType(valTy), valReg, v.llvmName))
	return out.String()
}

func (g *Generator) genAssignIndex(s *AssignIndexStmt) string {
	var out strings.Builder
	_, listReg, _ := g.genExpr(s.List, &out)
	_, idxReg, _ := g.genExpr(s.Index, &out)
	_, valReg, valTy := g.genExpr(s.Value, &out)

	elemLlvmTy := g.llvmType(valTy)

	dataFieldPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %%WhaleArray, ptr %s, i32 0, i32 1\n", dataFieldPtrReg, listReg))
	dataPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = load ptr, ptr %s\n", dataPtrReg, dataFieldPtrReg))

	elemPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %s, ptr %s, i64 %s\n", elemPtrReg, elemLlvmTy, dataPtrReg, idxReg))

	out.WriteString(fmt.Sprintf("  store %s %s, ptr %s\n", elemLlvmTy, valReg, elemPtrReg))

	return out.String()
}

func (g *Generator) genSpawn(s *SpawnStmt) string {
	g.declaredExterns["whale_spawn_worker"] = true
	g.declaredExterns["malloc"] = true
	g.declaredExterns["free"] = true

	var out strings.Builder
	
	argTypes := []Type{}
	argRegs := []string{}
	
	for _, a := range s.Call.Args {
		ir, reg, ty := g.genExpr(a, &out)
		out.WriteString(ir)
		argTypes = append(argTypes, ty)
		argRegs = append(argRegs, reg)
	}

	// Calculate struct size
	var llvmStructType strings.Builder
	llvmStructType.WriteString("{ ")
	for i, ty := range argTypes {
		if i > 0 { llvmStructType.WriteString(", ") }
		llvmStructType.WriteString(g.llvmType(ty))
	}
	llvmStructType.WriteString(" }")
	
	sizePtrReg := g.newTemp()
	sizeReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr %s, ptr null, i32 1\n", sizePtrReg, llvmStructType.String()))
	out.WriteString(fmt.Sprintf("  %s = ptrtoint ptr %s to i64\n", sizeReg, sizePtrReg))
	
	// Allocate struct
	argsPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = call ptr @malloc(i64 %s)\n", argsPtrReg, sizeReg))
	
	// Store arguments
	for i, reg := range argRegs {
		fieldPtrReg := g.newTemp()
		out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %s, ptr %s, i32 0, i32 %d\n", fieldPtrReg, llvmStructType.String(), argsPtrReg, i))
		out.WriteString(fmt.Sprintf("  store %s %s, ptr %s\n", g.llvmType(argTypes[i]), reg, fieldPtrReg))
	}

	// Trampoline name
	g.labelCount++
	trampName := fmt.Sprintf("spawn_tramp_%s_%d", s.Call.Callee, g.labelCount)

	// Call worker
	out.WriteString(fmt.Sprintf("  call void @whale_spawn_worker(ptr @%s, ptr %s)\n", trampName, argsPtrReg))

	// Generate trampoline
	var tramp strings.Builder
	tramp.WriteString(fmt.Sprintf("\ndefine ptr @%s(ptr %%args) {\n", trampName))
	tramp.WriteString("entry:\n")
	
	callArgs := []string{}
	for i, ty := range argTypes {
		fieldPtrReg := fmt.Sprintf("%%field.ptr.%d", i)
		fieldValReg := fmt.Sprintf("%%field.val.%d", i)
		tramp.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %s, ptr %%args, i32 0, i32 %d\n", fieldPtrReg, llvmStructType.String(), i))
		tramp.WriteString(fmt.Sprintf("  %s = load %s, ptr %s\n", fieldValReg, g.llvmType(ty), fieldPtrReg))
		callArgs = append(callArgs, fmt.Sprintf("%s %s", g.llvmType(ty), fieldValReg))
	}
	
	tramp.WriteString(fmt.Sprintf("  call %s @%s(%s)\n", g.llvmType(TypeVoid), s.Call.Callee, strings.Join(callArgs, ", ")))
	tramp.WriteString("  call void @free(ptr %args)\n")
	tramp.WriteString("  ret ptr null\n")
	tramp.WriteString("}\n")
	
	g.trampolines.WriteString(tramp.String())

	return out.String()
}

func (g *Generator) genChanSend(s *ChanSendStmt) string {
	g.declaredExterns["whale_chan_send"] = true
	var out strings.Builder
	
	chIR, chReg, _ := g.genExpr(s.Chan, &out)
	out.WriteString(chIR)
	
	valIR, valReg, _ := g.genExpr(s.Value, &out)
	out.WriteString(valIR)
	
	// whale_chan_send(ptr ch, i64 val)
	// We're passing the value as i64. For pointers, we'd theoretically need a bitcast to ptrtoint,
	// but test_spawn.wh only uses int over channels, so this MVP implementation relies on the C runtime handling it.
	out.WriteString(fmt.Sprintf("  call void @whale_chan_send(ptr %s, i64 %s)\n", chReg, valReg))
	
	return out.String()
}

func (g *Generator) genReturn(s *ReturnStmt) string {
	if s.Value == nil {
		return "  ret void\n"
	}
	var out strings.Builder
	ir, reg, ty := g.genExpr(s.Value, &out)
	return out.String() + ir + fmt.Sprintf("  ret %s %s\n", g.llvmType(ty), reg)
}

// genIf generates a standard three-block branch: cond -> then/else -> merge.
// This is the textbook LLVM pattern for if/else (see the Kaleidoscope
// tutorial in LLVM's own docs, which this mirrors closely on purpose ?
// it's the reference implementation to compare against).
func (g *Generator) genIf(s *IfStmt) (string, bool) {
	var out strings.Builder

	condIR, condReg, _ := g.genExpr(s.Cond, &out)
	out.WriteString(condIR)

	thenLabel := g.newLabel("if.then")
	elseLabel := g.newLabel("if.else")
	mergeLabel := g.newLabel("if.merge")

	if s.Else != nil {
		out.WriteString(fmt.Sprintf("  br i1 %s, label %%%s, label %%%s\n", condReg, thenLabel, elseLabel))
	} else {
		out.WriteString(fmt.Sprintf("  br i1 %s, label %%%s, label %%%s\n", condReg, thenLabel, mergeLabel))
	}

	out.WriteString(thenLabel + ":\n")
	thenIR, thenTerm := g.genBlock(s.Then)
	out.WriteString(thenIR)
	if !thenTerm {
		out.WriteString(fmt.Sprintf("  br label %%%s\n", mergeLabel))
	}

	elseTerm := false
	if s.Else != nil {
		out.WriteString(elseLabel + ":\n")
		elseIR, term := g.genBlock(s.Else)
		out.WriteString(elseIR)
		elseTerm = term
		if !elseTerm {
			out.WriteString(fmt.Sprintf("  br label %%%s\n", mergeLabel))
		}
	}

	// If both branches returned, the merge block is unreachable ? but we
	// still emit it (with an unreachable terminator) because some
	// caller code paths in genBlock expect a block to exist. This keeps
	// the IR simple and correct at the cost of one dead block, which
	// LLVM's optimizer trivially removes later (-O1 and above).
	bothTerminated := thenTerm && (s.Else == nil || elseTerm)
	out.WriteString(mergeLabel + ":\n")
	if bothTerminated {
		out.WriteString("  unreachable\n")
		return out.String(), true
	}
	return out.String(), false
}

func (g *Generator) genWhile(s *WhileStmt) (string, bool) {
	var out strings.Builder

	condLabel := g.newLabel("while.cond")
	bodyLabel := g.newLabel("while.body")
	endLabel := g.newLabel("while.end")

	out.WriteString(fmt.Sprintf("  br label %%%s\n", condLabel))
	out.WriteString(fmt.Sprintf("\n%s:\n", condLabel))

	condIR, condReg, _ := g.genExpr(s.Cond, &out)
	out.WriteString(condIR)
	out.WriteString(fmt.Sprintf("  br i1 %s, label %%%s, label %%%s\n", condReg, bodyLabel, endLabel))

	out.WriteString(fmt.Sprintf("\n%s:\n", bodyLabel))
	bodyIR, term := g.genBlock(s.Body)
	out.WriteString(bodyIR)
	if !term {
		out.WriteString(fmt.Sprintf("  br label %%%s\n", condLabel))
	}

	out.WriteString(fmt.Sprintf("\n%s:\n", endLabel))
	return out.String(), false
}

// ---------------------------------------------------------------------------
// Expression codegen
// ---------------------------------------------------------------------------

// genExpr returns (IR instructions to emit, the SSA register or literal
// holding the result, and the expression's Type).
func (g *Generator) genExpr(e Expr, out *strings.Builder) (string, string, Type) {
	switch ex := e.(type) {

	case *IntLit:
		return "", fmt.Sprintf("%d", ex.Value), TypeInt

	case *FloatLit:
		return "", fmt.Sprintf("%f", ex.Value), TypeFloat

	case *BoolLit:
		if ex.Value {
			return "", "1", TypeBool
		}
		return "", "0", TypeBool

	case *StringLit:
		globalName, length := g.internString(ex.Value)
		reg := g.newTemp()
		out.WriteString(fmt.Sprintf(
			"  %s = getelementptr inbounds [%d x i8], ptr %s, i64 0, i64 0\n",
			reg, length, globalName,
		))
		return "", reg, TypeString

	case *Ident:
		v, ok := g.scope[ex.Name]
		if !ok {
			panic(fmt.Sprintf("codegen: undefined variable %q", ex.Name))
		}
		reg := g.newTemp()
		out.WriteString(fmt.Sprintf("  %s = load %s, ptr %s\n", reg, g.llvmType(v.ty), v.llvmName))
		return "", reg, v.ty

	case *BinaryExpr:
		return g.genBinary(ex, out)

	case *CallExpr:
		return g.genCall(ex, out)

	case *StructLit:
		return g.genStructLit(ex, out)

	case *FieldAccess:
		return g.genFieldAccess(ex, out)

	case *ListLit:
		return g.genListLit(ex, out)

	case *IndexExpr:
		return g.genIndexExpr(ex, out)

	case *LenExpr:
		return g.genLenExpr(ex, out)

	case *AllocArray:
		return g.genAllocArray(ex, out)

	case *ConstructEnumExpr:
		return g.genConstructEnum(ex, out)

	case *MatchExpr:
		return g.genMatchExpr(ex, out)

	case *ChanRecvExpr:
		return g.genChanRecv(ex, out)

	default:
		panic(fmt.Sprintf("codegen: unhandled expression type %T", e))
	}
}

func (g *Generator) genBinary(ex *BinaryExpr, out *strings.Builder) (string, string, Type) {
	var body strings.Builder
	_, lReg, lTy := g.genExpr(ex.Left, &body)
	_, rReg, _ := g.genExpr(ex.Right, &body)

	reg := g.newTemp()
	op, isCmp := binaryOp(ex.Op, lTy)
	body.WriteString(fmt.Sprintf("  %s = %s %s %s, %s\n", reg, op, g.llvmType(lTy), lReg, rReg))

	if isCmp {
		return body.String(), reg, TypeBool
	}
	return body.String(), reg, lTy
}

// genCall handles function calls. print(...) is special-cased.
func (g *Generator) genCall(ex *CallExpr, out *strings.Builder) (string, string, Type) {
	if ex.Callee == "print" {
		return g.genPrintCall(ex, out)
	}

	var body strings.Builder
	argRegs := make([]string, len(ex.Args))
	argTypes := make([]Type, len(ex.Args))
	for i, a := range ex.Args {
		_, reg, ty := g.genExpr(a, &body)
		argRegs[i] = reg
		argTypes[i] = ty
	}

	argStrs := make([]string, len(ex.Args))
	for i := range ex.Args {
		argStrs[i] = fmt.Sprintf("%s %s", g.llvmType(argTypes[i]), argRegs[i])
	}

	calleeName := ex.Callee
	retTy := TypeInt // Default fallback for user functions

	switch ex.Callee {
	case "read_file": calleeName = "whale_read_file"; retTy = TypeString; g.declaredExterns[calleeName] = true
	case "write_file": calleeName = "whale_write_file"; retTy = TypeVoid; g.declaredExterns[calleeName] = true
	case "lines": calleeName = "whale_lines"; retTy = Type("[string]"); g.declaredExterns[calleeName] = true
	case "split": calleeName = "whale_split"; retTy = Type("[string]"); g.declaredExterns[calleeName] = true
	case "trim": calleeName = "whale_trim"; retTy = TypeString; g.declaredExterns[calleeName] = true
	case "replace": calleeName = "whale_replace"; retTy = TypeString; g.declaredExterns[calleeName] = true
	case "to_lower": calleeName = "whale_to_lower"; retTy = TypeString; g.declaredExterns[calleeName] = true
	case "to_upper": calleeName = "whale_to_upper"; retTy = TypeString; g.declaredExterns[calleeName] = true
	case "abs":
		if argTypes[0] == TypeFloat { calleeName = "whale_abs_f"; retTy = TypeFloat } else { calleeName = "whale_abs_i"; retTy = TypeInt }
		g.declaredExterns[calleeName] = true
	case "max":
		if argTypes[0] == TypeFloat { calleeName = "whale_max_f"; retTy = TypeFloat } else { calleeName = "whale_max_i"; retTy = TypeInt }
		g.declaredExterns[calleeName] = true
	case "min":
		if argTypes[0] == TypeFloat { calleeName = "whale_min_f"; retTy = TypeFloat } else { calleeName = "whale_min_i"; retTy = TypeInt }
		g.declaredExterns[calleeName] = true
	case "parse_int": calleeName = "whale_parse_int"; retTy = TypeInt; g.declaredExterns[calleeName] = true
	case "push": calleeName = "whale_push"; retTy = argTypes[0]; g.declaredExterns[calleeName] = true
	case "pop": calleeName = "whale_pop"; retTy = argTypes[0]; g.declaredExterns[calleeName] = true
	case "make_chan": calleeName = "whale_chan_new"; retTy = Type("chan"); g.declaredExterns[calleeName] = true
	}

	reg := g.newTemp()
	body.WriteString(fmt.Sprintf("  %s = call %s @%s(%s)\n", reg, g.llvmType(retTy), calleeName, strings.Join(argStrs, ", ")))
	return body.String(), reg, retTy
}

func (g *Generator) genChanRecv(ex *ChanRecvExpr, out *strings.Builder) (string, string, Type) {
	g.declaredExterns["whale_chan_recv"] = true
	var body strings.Builder
	_, chReg, _ := g.genExpr(ex.Chan, &body)
	
	valReg := g.newTemp()
	body.WriteString(fmt.Sprintf("  %s = call i64 @whale_chan_recv(ptr %s)\n", valReg, chReg))
	
	// Assume we are receiving int64 for MVP.
	return body.String(), valReg, TypeInt
}

// genPrintCall lowers print(x) to a call to libc's printf.
func (g *Generator) genPrintCall(ex *CallExpr, out *strings.Builder) (string, string, Type) {
	g.declaredExterns["printf"] = true
	var body strings.Builder
	
	var fmtStr strings.Builder
	argRegs := []string{}
	argTypes := []Type{}
	
	for _, arg := range ex.Args {
		_, argReg, argTy := g.genExpr(arg, &body)
		argRegs = append(argRegs, argReg)
		argTypes = append(argTypes, argTy)
		
		switch argTy {
		case TypeInt: fmtStr.WriteString("%ld")
		case TypeFloat: fmtStr.WriteString("%f")
		case TypeBool: fmtStr.WriteString("%d")
		case TypeString: fmtStr.WriteString("%s")
		default: panic("unsupported print type: " + argTy)
		}
	}
	fmtStr.WriteString("\n")
	
	fmtGlobal, fmtLen := g.internString(fmtStr.String())
	fmtPtrReg := g.newTemp()
	body.WriteString(fmt.Sprintf("  %s = getelementptr inbounds [%d x i8], ptr %s, i64 0, i64 0\n", fmtPtrReg, fmtLen, fmtGlobal))

	var callArgs strings.Builder
	callArgs.WriteString(fmt.Sprintf("ptr %s", fmtPtrReg))
	for i, reg := range argRegs {
		callArgs.WriteString(fmt.Sprintf(", %s %s", g.llvmType(argTypes[i]), reg))
	}
	
	resultReg := g.newTemp()
	body.WriteString(fmt.Sprintf("  %s = call i32 (ptr, ...) @printf(%s)\n", resultReg, callArgs.String()))
	return body.String(), resultReg, TypeInt
}

// ---------------------------------------------------------------------------
// Struct codegen
// ---------------------------------------------------------------------------

func (g *Generator) genStructLit(node *StructLit, out *strings.Builder) (string, string, Type) {
	g.declaredExterns["whale_malloc"] = true
	structDecl := g.structs[node.StructName]

	sizePtrReg := g.newTemp()
	sizeReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr %%struct.%s, ptr null, i32 1\n", sizePtrReg, node.StructName))
	out.WriteString(fmt.Sprintf("  %s = ptrtoint ptr %s to i64\n", sizeReg, sizePtrReg))

	ptrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = call ptr @whale_malloc(i64 %s)\n", ptrReg, sizeReg))

	for i, param := range structDecl.Fields {
		_, valReg, valTy := g.genExpr(node.Fields[param.Name], out)
		fieldPtrReg := g.newTemp()
		out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %%struct.%s, ptr %s, i32 0, i32 %d\n", fieldPtrReg, node.StructName, ptrReg, i))
		out.WriteString(fmt.Sprintf("  store %s %s, ptr %s\n", g.llvmType(valTy), valReg, fieldPtrReg))
	}
	return "", ptrReg, Type(node.StructName)
}

func (g *Generator) genConstructEnum(ex *ConstructEnumExpr, out *strings.Builder) (string, string, Type) {
	ptr := g.newTemp()
	enumTypeStr := "%enum." + ex.EnumName
	
	// Enums are usually returned as ptr, but structs are usually passed by allocating a temporary.
	out.WriteString(fmt.Sprintf("  %s = alloca %s\n", ptr, enumTypeStr))
	
	enumDecl := g.enums[ex.EnumName]
	tagIndex := 0
	var payloadType Type = ""
	for i, v := range enumDecl.Variants {
		if v.Name == ex.Variant {
			tagIndex = i
			payloadType = v.Type
			break
		}
	}
	
	// Store tag
	tagPtr := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %s, ptr %s, i32 0, i32 0\n", tagPtr, enumTypeStr, ptr))
	out.WriteString(fmt.Sprintf("  store i32 %d, ptr %s\n", tagIndex, tagPtr))
	
	// Store payload
	if ex.Payload != nil {
		_, pReg, _ := g.genExpr(ex.Payload, out)
		payloadFieldIndex := 1
		for _, v := range enumDecl.Variants {
			if v.Name == ex.Variant {
				break
			}
			if v.Type != "" {
				payloadFieldIndex++
			}
		}
		
		payloadPtr := g.newTemp()
		out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %s, ptr %s, i32 0, i32 %d\n", payloadPtr, enumTypeStr, ptr, payloadFieldIndex))
		out.WriteString(fmt.Sprintf("  store %s %s, ptr %s\n", g.llvmType(payloadType), pReg, payloadPtr))
	}
	
	return "", ptr, Type(ex.EnumName)
}

func (g *Generator) genMatchExpr(ex *MatchExpr, out *strings.Builder) (string, string, Type) {
	_, ptrReg, enumTy := g.genExpr(ex.Expr, out)
	
	enumName := string(enumTy)
	enumDecl := g.enums[enumName]
	enumTypeStr := "%enum." + enumName
	
	// Load the tag
	tagPtr := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %s, ptr %s, i32 0, i32 0\n", tagPtr, enumTypeStr, ptrReg))
	
	tagReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = load i32, ptr %s\n", tagReg, tagPtr))
	
	// Generate basic blocks for branches
	var armBlocks []string
	var phiBlocks []string
	var phiRegs []string
	
	defaultBlock := g.newLabel("match.default")
	endBlock := g.newLabel("match.end")
	
	out.WriteString(fmt.Sprintf("  switch i32 %s, label %%%s [\n", tagReg, defaultBlock))
	
	hasCatchAll := false
	var catchAllBlock string
	
	// First pass: generate the switch table
	for _, arm := range ex.Arms {
		if arm.IsCatchAll {
			hasCatchAll = true
			catchAllBlock = g.newLabel("match.arm.catchall")
		} else {
			tagIndex := 0
			for i, v := range enumDecl.Variants {
				if v.Name == arm.Variant {
					tagIndex = i
					break
				}
			}
			block := g.newLabel(fmt.Sprintf("match.arm.%s", arm.Variant))
			out.WriteString(fmt.Sprintf("    i32 %d, label %%%s\n", tagIndex, block))
			armBlocks = append(armBlocks, block)
		}
	}
	out.WriteString("  ]\n\n")
	
	// Generate Default block
	out.WriteString(defaultBlock + ":\n")
	if hasCatchAll {
		out.WriteString(fmt.Sprintf("  br label %%%s\n\n", catchAllBlock))
	} else {
		out.WriteString("  unreachable\n\n")
	}
	
	var unifiedType Type = TypeVoid
	
	// Generate Arms
	armIdx := 0
	for _, arm := range ex.Arms {
		var block string
		if arm.IsCatchAll {
			block = catchAllBlock
		} else {
			block = armBlocks[armIdx]
			armIdx++
		}
		
		out.WriteString(block + ":\n")
		
		if arm.Binding != "" && !arm.IsCatchAll {
			var payloadType Type = ""
			for _, v := range enumDecl.Variants {
				if v.Name == arm.Variant {
					payloadType = v.Type
					break
				}
			}
			
			payloadFieldIndex := 1
			for _, v := range enumDecl.Variants {
				if v.Name == arm.Variant {
					break
				}
				if v.Type != "" {
					payloadFieldIndex++
				}
			}
			
			payloadPtr := g.newTemp()
			out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %s, ptr %s, i32 0, i32 %d\n", payloadPtr, enumTypeStr, ptrReg, payloadFieldIndex))
			
			payloadReg := g.newTemp()
			out.WriteString(fmt.Sprintf("  %s = load %s, ptr %s\n", payloadReg, g.llvmType(payloadType), payloadPtr))
			
			bindingPtr := g.newTemp()
			out.WriteString(fmt.Sprintf("  %s = alloca %s\n", bindingPtr, g.llvmType(payloadType)))
			out.WriteString(fmt.Sprintf("  store %s %s, ptr %s\n", g.llvmType(payloadType), payloadReg, bindingPtr))
			
			g.scope[arm.Binding] = scopedVar{llvmName: bindingPtr, ty: payloadType}
		}
		
		_, bodyReg, bodyTy := g.genExpr(arm.Body, out)
		
		if arm.Binding != "" {
			delete(g.scope, arm.Binding)
		}
		
		exitBlock := g.newLabel("match.arm.exit")
		out.WriteString(fmt.Sprintf("  br label %%%s\n\n", exitBlock))
		out.WriteString(exitBlock + ":\n")
		
		if bodyTy != TypeVoid {
			phiRegs = append(phiRegs, bodyReg)
			phiBlocks = append(phiBlocks, exitBlock)
			unifiedType = bodyTy
		}
		
		out.WriteString(fmt.Sprintf("  br label %%%s\n\n", endBlock))
	}
	
	// Generate end block
	out.WriteString(endBlock + ":\n")
	
	resultReg := ""
	if unifiedType != TypeVoid && len(phiRegs) > 0 {
		resultReg = g.newTemp()
		out.WriteString(fmt.Sprintf("  %s = phi %s ", resultReg, g.llvmType(unifiedType)))
		
		for i := 0; i < len(phiRegs); i++ {
			if i > 0 {
				out.WriteString(", ")
			}
			out.WriteString(fmt.Sprintf("[ %s, %%%s ]", phiRegs[i], phiBlocks[i]))
		}
		out.WriteString("\n")
	}
	
	return "", resultReg, unifiedType
}

func (g *Generator) genFieldAccess(node *FieldAccess, out *strings.Builder) (string, string, Type) {
	_, objReg, objTy := g.genExpr(node.Object, out)
	structDecl := g.structs[string(objTy)]

	fieldIdx := 0
	var fieldTy Type
	for i, param := range structDecl.Fields {
		if param.Name == node.Field {
			fieldIdx = i
			fieldTy = param.Type
		}
	}

	fieldPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %%struct.%s, ptr %s, i32 0, i32 %d\n", fieldPtrReg, string(objTy), objReg, fieldIdx))
	valReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = load %s, ptr %s\n", valReg, g.llvmType(fieldTy), fieldPtrReg))
	return "", valReg, fieldTy
}

// ---------------------------------------------------------------------------
// Array codegen
// ---------------------------------------------------------------------------

func (g *Generator) genListLit(node *ListLit, out *strings.Builder) (string, string, Type) {
	g.declaredExterns["whale_malloc"] = true

	sizePtrReg := g.newTemp()
	sizeReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr %%WhaleArray, ptr null, i32 1\n", sizePtrReg))
	out.WriteString(fmt.Sprintf("  %s = ptrtoint ptr %s to i64\n", sizeReg, sizePtrReg))
	arrPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = call ptr @whale_malloc(i64 %s)\n", arrPtrReg, sizeReg))

	length := len(node.Values)
	lenPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %%WhaleArray, ptr %s, i32 0, i32 0\n", lenPtrReg, arrPtrReg))
	out.WriteString(fmt.Sprintf("  store i64 %d, ptr %s\n", length, lenPtrReg))

	dataSizePtrReg := g.newTemp()
	dataSizeReg := g.newTemp()
	elemLlvmTy := g.llvmType(node.ElementType)
	out.WriteString(fmt.Sprintf("  %s = getelementptr %s, ptr null, i32 1\n", dataSizePtrReg, elemLlvmTy))
	out.WriteString(fmt.Sprintf("  %s = ptrtoint ptr %s to i64\n", dataSizeReg, dataSizePtrReg))
	
	totalBytesReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = mul i64 %s, %d\n", totalBytesReg, dataSizeReg, length))
	dataPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = call ptr @whale_malloc(i64 %s)\n", dataPtrReg, totalBytesReg))

	dataFieldPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %%WhaleArray, ptr %s, i32 0, i32 1\n", dataFieldPtrReg, arrPtrReg))
	out.WriteString(fmt.Sprintf("  store ptr %s, ptr %s\n", dataPtrReg, dataFieldPtrReg))

	for i, v := range node.Values {
		_, valReg, valTy := g.genExpr(v, out)
		elemPtrReg := g.newTemp()
		out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %s, ptr %s, i64 %d\n", elemPtrReg, elemLlvmTy, dataPtrReg, i))
		out.WriteString(fmt.Sprintf("  store %s %s, ptr %s\n", g.llvmType(valTy), valReg, elemPtrReg))
	}

	return "", arrPtrReg, Type("[" + string(node.ElementType) + "]")
}

func (g *Generator) genIndexExpr(node *IndexExpr, out *strings.Builder) (string, string, Type) {
	_, listReg, listTy := g.genExpr(node.List, out)
	_, idxReg, _ := g.genExpr(node.Index, out)

	listTyStr := string(listTy)
	elemTy := Type(listTyStr[1 : len(listTyStr)-1])
	elemLlvmTy := g.llvmType(elemTy)

	dataFieldPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %%WhaleArray, ptr %s, i32 0, i32 1\n", dataFieldPtrReg, listReg))
	dataPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = load ptr, ptr %s\n", dataPtrReg, dataFieldPtrReg))

	elemPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %s, ptr %s, i64 %s\n", elemPtrReg, elemLlvmTy, dataPtrReg, idxReg))

	valReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = load %s, ptr %s\n", valReg, elemLlvmTy, elemPtrReg))

	return "", valReg, elemTy
}

func (g *Generator) genLenExpr(node *LenExpr, out *strings.Builder) (string, string, Type) {
	_, listReg, _ := g.genExpr(node.List, out)
	lenPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %%WhaleArray, ptr %s, i32 0, i32 0\n", lenPtrReg, listReg))
	lenReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = load i64, ptr %s\n", lenReg, lenPtrReg))
	return "", lenReg, TypeInt
}

func (g *Generator) genAllocArray(node *AllocArray, out *strings.Builder) (string, string, Type) {
	g.declaredExterns["whale_malloc"] = true
	_, lenReg, _ := g.genExpr(node.Length, out)

	sizePtrReg := g.newTemp()
	sizeReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr %%WhaleArray, ptr null, i32 1\n", sizePtrReg))
	out.WriteString(fmt.Sprintf("  %s = ptrtoint ptr %s to i64\n", sizeReg, sizePtrReg))
	arrPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = call ptr @whale_malloc(i64 %s)\n", arrPtrReg, sizeReg))

	lenPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %%WhaleArray, ptr %s, i32 0, i32 0\n", lenPtrReg, arrPtrReg))
	out.WriteString(fmt.Sprintf("  store i64 %s, ptr %s\n", lenReg, lenPtrReg))

	dataSizePtrReg := g.newTemp()
	dataSizeReg := g.newTemp()
	elemLlvmTy := g.llvmType(node.ElementType)
	out.WriteString(fmt.Sprintf("  %s = getelementptr %s, ptr null, i32 1\n", dataSizePtrReg, elemLlvmTy))
	out.WriteString(fmt.Sprintf("  %s = ptrtoint ptr %s to i64\n", dataSizeReg, dataSizePtrReg))
	
	totalBytesReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = mul i64 %s, %s\n", totalBytesReg, dataSizeReg, lenReg))
	dataPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = call ptr @whale_malloc(i64 %s)\n", dataPtrReg, totalBytesReg))

	dataFieldPtrReg := g.newTemp()
	out.WriteString(fmt.Sprintf("  %s = getelementptr inbounds %%WhaleArray, ptr %s, i32 0, i32 1\n", dataFieldPtrReg, arrPtrReg))
	out.WriteString(fmt.Sprintf("  store ptr %s, ptr %s\n", dataPtrReg, dataFieldPtrReg))

	return "", arrPtrReg, Type("[" + string(node.ElementType) + "]")
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func (g *Generator) newTemp() string {
	name := fmt.Sprintf("%%t%d", g.tmpCount)
	g.tmpCount++
	return name
}

func (g *Generator) newLabel(prefix string) string {
	name := fmt.Sprintf("%s.%d", prefix, g.labelCount)
	g.labelCount++
	return name
}

// internString deduplicates string literals, returning the global constant
// name and the length (including null terminator, since LLVM needs it).
func (g *Generator) internString(s string) (string, int) {
	for _, sc := range g.stringConstants {
		if sc.value == s {
			return sc.globalName, sc.length
		}
	}
	name := fmt.Sprintf("@.str.%d", len(g.stringConstants))
	length := len(s) + 1 // +1 for the trailing null byte
	g.stringConstants = append(g.stringConstants, stringConst{
		globalName: name, value: s, length: length,
	})
	return name, length
}

func (g *Generator) exprType(e Expr) Type {
	switch ex := e.(type) {
	case *IntLit:
		return TypeInt
	case *FloatLit:
		return TypeFloat
	case *BoolLit:
		return TypeBool
	case *StringLit:
		return TypeString
	case *Ident:
		return g.scope[ex.Name].ty
	case *BinaryExpr:
		if isComparisonOp(ex.Op) {
			return TypeBool
		}
		return g.exprType(ex.Left)
	case *CallExpr:
		return TypeInt // see note in genCall about hardcoded return type
	case *StructLit:
		return Type(ex.StructName)
	case *ListLit:
		return Type("[" + string(ex.ElementType) + "]")
	case *IndexExpr:
		listTy := string(g.exprType(ex.List))
		if strings.HasPrefix(listTy, "[") && strings.HasSuffix(listTy, "]") {
			return Type(listTy[1 : len(listTy)-1])
		}
		return TypeInt
	case *LenExpr:
		return TypeInt
	case *AllocArray:
		return Type("[" + string(ex.ElementType) + "]")
	case *FieldAccess:
		objTy := g.exprType(ex.Object)
		structDecl, ok := g.structs[string(objTy)]
		if !ok {
			return TypeInt
		}
		for _, p := range structDecl.Fields {
			if p.Name == ex.Field {
				return p.Type
			}
		}
		return TypeInt
	default:
		panic(fmt.Sprintf("codegen: exprType: unhandled expression type %T", e))
	}
}

func (g *Generator) llvmType(t Type) string {
	switch t {
	case TypeInt:
		return "i64"
	case TypeFloat:
		return "double"
	case TypeBool:
		return "i1"
	case TypeString:
		return "ptr"
	case TypeVoid:
		return "void"
	default:
		if strings.HasPrefix(string(t), "[") || strings.HasPrefix(string(t), "list") {
			return "ptr" // %WhaleArray*
		}
		if _, ok := g.structs[string(t)]; ok {
			return "ptr" // structs are passed by reference
		}
		if _, ok := g.enums[string(t)]; ok {
			return "ptr" // enums are passed by reference
		}
		if strings.HasPrefix(string(t), "chan") {
			return "ptr" // channels are opaque pointers
		}
		panic(fmt.Sprintf("codegen: unhandled Type %v", t))
	}
}

func zeroValue(t Type) string {
	switch t {
	case TypeInt:
		return "0"
	case TypeFloat:
		return "0.0"
	case TypeBool:
		return "0"
	case TypeString:
		return "null"
	default:
		return "null"
	}
}

func externDecl(name string) string {
	switch name {
	case "printf":
		return "declare i32 @printf(ptr, ...)\n"
	case "malloc":
		return "declare ptr @malloc(i64)\n"
	case "whale_malloc":
		return "declare ptr @whale_malloc(i64)\n"
	case "whale_gc_init":
		return "declare void @whale_gc_init(ptr)\n"
	case "whale_read_file":
		return "declare ptr @whale_read_file(ptr)\n"
	case "whale_write_file":
		return "declare void @whale_write_file(ptr, ptr)\n"
	case "whale_lines":
		return "declare %WhaleArray @whale_lines(ptr)\n"
	case "whale_split":
		return "declare %WhaleArray @whale_split(ptr, ptr)\n"
	case "whale_trim":
		return "declare ptr @whale_trim(ptr)\n"
	case "whale_replace":
		return "declare ptr @whale_replace(ptr, ptr, ptr)\n"
	case "whale_to_lower":
		return "declare ptr @whale_to_lower(ptr)\n"
	case "whale_spawn_worker":
		return "declare void @whale_spawn_worker(ptr, ptr)\n"
	case "whale_chan_new":
		return "declare ptr @whale_chan_new()\n"
	case "whale_chan_send":
		return "declare void @whale_chan_send(ptr, i64)\n"
	case "whale_chan_recv":
		return "declare i64 @whale_chan_recv(ptr)\n"
	case "free":
		return "declare void @free(ptr)\n"
	case "whale_net_listen":
		return "declare i64 @whale_net_listen(i64)\n"
	case "whale_net_accept":
		return "declare i64 @whale_net_accept(i64)\n"
	case "whale_net_recv":
		return "declare ptr @whale_net_recv(i64)\n"
	case "whale_net_send":
		return "declare void @whale_net_send(i64, ptr)\n"
	case "whale_net_close":
		return "declare void @whale_net_close(i64)\n"
	case "whale_net_dial":
		return "declare i64 @whale_net_dial(ptr, i64)\n"
	case "whale_map_new":
		return "declare i64 @whale_map_new()\n"
	case "whale_map_set":
		return "declare void @whale_map_set(i64, ptr, ptr)\n"
	case "whale_map_get":
		return "declare ptr @whale_map_get(i64, ptr)\n"
	case "whale_to_upper":
		return "declare ptr @whale_to_upper(ptr)\n"
	case "whale_abs_f":
		return "declare double @whale_abs_f(double)\n"
	case "whale_abs_i":
		return "declare i64 @whale_abs_i(i64)\n"
	case "whale_max_f":
		return "declare double @whale_max_f(double, double)\n"
	case "whale_max_i":
		return "declare i64 @whale_max_i(i64, i64)\n"
	case "whale_min_f":
		return "declare double @whale_min_f(double, double)\n"
	case "whale_min_i":
		return "declare i64 @whale_min_i(i64, i64)\n"
	case "whale_parse_int":
		return "declare i64 @whale_parse_int(ptr)\n"
	case "whale_push":
		// whale_push returns a WhaleArray and takes (WhaleArray, i64). But arrays in C are passed by value for simple structs (pass by register or memory depending on ABI). LLVM supports passing structs by value directly.
		return "declare %WhaleArray @whale_push(%WhaleArray, i64)\n"
	case "whale_pop":
		return "declare %WhaleArray @whale_pop(%WhaleArray)\n"
	default:
		panic(fmt.Sprintf("codegen: no extern declaration registered for %q", name))
	}
}

func llvmEscapeString(s string) string {
	var out strings.Builder
	for _, b := range []byte(s) {
		if b >= 0x20 && b < 0x7f && b != '"' && b != '\\' {
			out.WriteByte(b)
		} else {
			out.WriteString(fmt.Sprintf("\\%02X", b))
		}
	}
	out.WriteString("\\00") // null terminator
	return out.String()
}

func binaryOp(op string, ty Type) (string, bool) {
	if ty == TypeFloat {
		switch op {
		case "+":
			return "fadd", false
		case "-":
			return "fsub", false
		case "*":
			return "fmul", false
		case "/":
			return "fdiv", false
		case "==":
			return "fcmp oeq", true
		case "!=":
			return "fcmp one", true
		case "<":
			return "fcmp olt", true
		case "<=":
			return "fcmp ole", true
		case ">":
			return "fcmp ogt", true
		case ">=":
			return "fcmp oge", true
		default:
			panic("codegen: unknown float binary op: " + op)
		}
	}
	switch op {
	case "+":
		return "add", false
	case "-":
		return "sub", false
	case "*":
		return "mul", false
	case "/":
		return "sdiv", false
	case "==":
		return "icmp eq", true
	case "!=":
		return "icmp ne", true
	case "<":
		return "icmp slt", true
	case "<=":
		return "icmp sle", true
	case ">":
		return "icmp sgt", true
	case ">=":
		return "icmp sge", true
	default:
		panic("codegen: unknown int binary op: " + op)
	}
}

func isComparisonOp(op string) bool {
	switch op {
	case "==", "!=", "<", "<=", ">", ">=":
		return true
	}
	return false
}
