; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare void @whale_gc_init(ptr)

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [6 x i8] c"Hello\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"%s\0A\00"

define void @main() {
entry:
  %gc_stack_top = alloca i32
  call void @whale_gc_init(ptr %gc_stack_top)
  %t1 = getelementptr inbounds [6 x i8], ptr @.str.0, i64 0, i64 0
  %t2 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t3 = call i32 (ptr, ...) @printf(ptr %t2, ptr %t1)
  ret void
}

