; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare void @whale_gc_init(ptr)

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [25 x i8] c"Testing the math module!\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.2 = private unnamed_addr constant [20 x i8] c"math.add(10, 20) = \00"
@.str.3 = private unnamed_addr constant [7 x i8] c"%s%ld\0A\00"
@.str.4 = private unnamed_addr constant [16 x i8] c"math.area(5) = \00"
@.str.5 = private unnamed_addr constant [13 x i8] c"math.pi() = \00"

define i64 @math_pi() {
entry:
  ret i64 3
}

define i64 @math_add(i64 %a.arg, i64 %b.arg) {
entry:
  %a = alloca i64
  store i64 %a.arg, ptr %a
  %b = alloca i64
  store i64 %b.arg, ptr %b
  %t1 = load i64, ptr %a
  %t2 = load i64, ptr %b
  %t3 = add i64 %t1, %t2
  ret i64 %t3
}

define i64 @math_area(i64 %r.arg) {
entry:
  %r = alloca i64
  store i64 %r.arg, ptr %r
  %t4 = load i64, ptr %r
  %t5 = mul i64 %t3, %t4
  ret i64 %t5
}

define void @main() {
entry:
  %gc_stack_top = alloca i32
  call void @whale_gc_init(ptr %gc_stack_top)
  %t1 = getelementptr inbounds [25 x i8], ptr @.str.0, i64 0, i64 0
  %t2 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t3 = call i32 (ptr, ...) @printf(ptr %t2, ptr %t1)
  %t4 = call i64 @math_add(i64 10, i64 20)
  %sum = alloca i64
  store i64 %t4, ptr %sum
  %t5 = getelementptr inbounds [20 x i8], ptr @.str.2, i64 0, i64 0
  %t6 = load i64, ptr %sum
  %t7 = getelementptr inbounds [7 x i8], ptr @.str.3, i64 0, i64 0
  %t8 = call i32 (ptr, ...) @printf(ptr %t7, ptr %t5, i64 %t6)
  %t9 = call i64 @math_area(i64 5)
  %a = alloca i64
  store i64 %t9, ptr %a
  %t10 = getelementptr inbounds [16 x i8], ptr @.str.4, i64 0, i64 0
  %t11 = load i64, ptr %a
  %t12 = getelementptr inbounds [7 x i8], ptr @.str.3, i64 0, i64 0
  %t13 = call i32 (ptr, ...) @printf(ptr %t12, ptr %t10, i64 %t11)
  %t14 = getelementptr inbounds [13 x i8], ptr @.str.5, i64 0, i64 0
  %t16 = getelementptr inbounds [7 x i8], ptr @.str.3, i64 0, i64 0
  %t17 = call i32 (ptr, ...) @printf(ptr %t16, ptr %t14, i64 %t15)
  ret void
}

