; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare void @whale_gc_init(ptr)

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"

define void @main() {
entry:
  %gc_stack_top = alloca i32
  call void @whale_gc_init(ptr %gc_stack_top)
  %x = alloca i64
  store i64 42, ptr %x
  %ptr = alloca ptr
  store ptr %x, ptr %ptr
  %t3 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t4 = call i32 (ptr, ...) @printf(ptr %t3, i64 %t2)
  %t5 = load ptr, ptr %ptr
  store i64 100, ptr %t5
  %t6 = load i64, ptr %x
  %t7 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t8 = call i32 (ptr, ...) @printf(ptr %t7, i64 %t6)
  ret void
}

