; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare void @whale_gc_init(ptr)

declare i64 @puts(ptr)

@.str.0 = private unnamed_addr constant [49 x i8] c"Hello from external C library using Whale C-FFI!\00"

define void @main() {
entry:
  %gc_stack_top = alloca i32
  call void @whale_gc_init(ptr %gc_stack_top)
  %t1 = getelementptr inbounds [49 x i8], ptr @.str.0, i64 0, i64 0
  %t2 = call i64 @puts(ptr %t1)
  ret void
}

