; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare void @whale_gc_init(ptr)

declare void @whale_arena_push()

declare i32 @printf(ptr, ...)

declare void @whale_arena_pop()


@.str.0 = private unnamed_addr constant [15 x i8] c"Inside arena: \00"
@.str.1 = private unnamed_addr constant [7 x i8] c"%s%ld\0A\00"

define void @main() {
entry:
  %gc_stack_top = alloca i32
  call void @whale_gc_init(ptr %gc_stack_top)
  call void @whale_arena_push()
  %x = alloca i64
  store i64 10, ptr %x
  %t1 = getelementptr inbounds [15 x i8], ptr @.str.0, i64 0, i64 0
  %t2 = load i64, ptr %x
  %t3 = getelementptr inbounds [7 x i8], ptr @.str.1, i64 0, i64 0
  %t4 = call i32 (ptr, ...) @printf(ptr %t3, ptr %t1, i64 %t2)
  call void @whale_arena_pop()
  ret void
}

