; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

%struct.Node = type { i64, ptr }

declare void @whale_gc_init(ptr)

declare i32 @printf(ptr, ...)

declare ptr @whale_malloc(i64)


@.str.0 = private unnamed_addr constant [27 x i8] c"Starting GC stress test...\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.2 = private unnamed_addr constant [39 x i8] c"GC stress test completed successfully!\00"

define void @main() {
entry:
  %gc_stack_top = alloca i32
  call void @whale_gc_init(ptr %gc_stack_top)
  %t1 = getelementptr inbounds [27 x i8], ptr @.str.0, i64 0, i64 0
  %t2 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t3 = call i32 (ptr, ...) @printf(ptr %t2, ptr %t1)
  %i = alloca i64
  store i64 0, ptr %i
  br label %while.cond.1

while.cond.1:
  %t4 = load i64, ptr %i
  %t5 = icmp slt i64 %t4, 100000
  br i1 %t5, label %while.body.2, label %while.end.3

while.body.2:
  %t6 = getelementptr %struct.Node, ptr null, i32 1
  %t7 = ptrtoint ptr %t6 to i64
  %t8 = call ptr @whale_malloc(i64 %t7)
  %t9 = load i64, ptr %i
  %t10 = getelementptr inbounds %struct.Node, ptr %t8, i32 0, i32 0
  store i64 %t9, ptr %t10
  %t11 = getelementptr %WhaleArray, ptr null, i32 1
  %t12 = ptrtoint ptr %t11 to i64
  %t13 = call ptr @whale_malloc(i64 %t12)
  %t14 = getelementptr inbounds %WhaleArray, ptr %t13, i32 0, i32 0
  store i64 3, ptr %t14
  %t15 = getelementptr i64, ptr null, i32 1
  %t16 = ptrtoint ptr %t15 to i64
  %t17 = mul i64 %t16, 3
  %t18 = call ptr @whale_malloc(i64 %t17)
  %t19 = getelementptr inbounds %WhaleArray, ptr %t13, i32 0, i32 1
  store ptr %t18, ptr %t19
  %t20 = load i64, ptr %i
  %t21 = getelementptr inbounds i64, ptr %t18, i64 0
  store i64 %t20, ptr %t21
  %t24 = getelementptr inbounds i64, ptr %t18, i64 1
  store i64 %t23, ptr %t24
  %t27 = getelementptr inbounds i64, ptr %t18, i64 2
  store i64 %t26, ptr %t27
  %t28 = getelementptr inbounds %struct.Node, ptr %t8, i32 0, i32 1
  store ptr %t13, ptr %t28
  %n = alloca ptr
  store ptr %t8, ptr %n
  store i64 %t30, ptr %i
  br label %while.cond.1

while.end.3:
  %t31 = getelementptr inbounds [39 x i8], ptr @.str.2, i64 0, i64 0
  %t32 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t33 = call i32 (ptr, ...) @printf(ptr %t32, ptr %t31)
  ret void
}

