; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

%struct.Packet = type <{ i4, i4, i12 }>

declare void @whale_gc_init(ptr)

declare ptr @whale_malloc(i64)

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [9 x i8] c"Header: \00"
@.str.1 = private unnamed_addr constant [6 x i8] c"%s%u\0A\00"

define void @main() {
entry:
  %gc_stack_top = alloca i32
  call void @whale_gc_init(ptr %gc_stack_top)
  %t1 = getelementptr %struct.Packet, ptr null, i32 1
  %t2 = ptrtoint ptr %t1 to i64
  %t3 = call ptr @whale_malloc(i64 %t2)
  %t4 = trunc i64 10 to i4
  %t5 = getelementptr inbounds %struct.Packet, ptr %t3, i32 0, i32 0
  store i4 %t4, ptr %t5
  %t6 = trunc i64 1 to i4
  %t7 = getelementptr inbounds %struct.Packet, ptr %t3, i32 0, i32 1
  store i4 %t6, ptr %t7
  %t8 = trunc i64 4095 to i12
  %t9 = getelementptr inbounds %struct.Packet, ptr %t3, i32 0, i32 2
  store i12 %t8, ptr %t9
  %p = alloca ptr
  store ptr %t3, ptr %p
  %t10 = getelementptr inbounds [9 x i8], ptr @.str.0, i64 0, i64 0
  %t11 = load ptr, ptr %p
  %t12 = getelementptr inbounds %struct.Packet, ptr %t11, i32 0, i32 0
  %t13 = load i4, ptr %t12
  %t14 = getelementptr inbounds [6 x i8], ptr @.str.1, i64 0, i64 0
  %t15 = call i32 (ptr, ...) @printf(ptr %t14, ptr %t10, i4 %t13)
  ret void
}

