; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare void @whale_gc_init(ptr)

declare i32 @printf(ptr, ...)

declare i64 @malloc(i64)
declare void @free(i64)
declare i64 @memcpy(i64, i64, i64)
declare i64 @realloc(i64, i64)
declare i64 @strlen(ptr)
declare i64 @strcmp(ptr, ptr)
declare i64 @fopen(ptr, ptr)
declare i64 @fclose(i64)
declare i64 @fread(i64, i64, i64, i64)
declare i64 @fwrite(i64, i64, i64, i64)
declare i64 @socket(i64, i64, i64)
declare i64 @connect(i64, i64, i64)
declare i64 @send(i64, i64, i64, i64)
declare i64 @recv(i64, i64, i64, i64)
declare i64 @time(i64)

@.str.0 = private unnamed_addr constant [48 x i8] c"Whale C-FFI is incredibly fast and memory safe!\00"
@.str.1 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"
@.str.2 = private unnamed_addr constant [16 x i8] c"test_output.txt\00"
@.str.3 = private unnamed_addr constant [2 x i8] c"w\00"
@.str.4 = private unnamed_addr constant [47 x i8] c"Standard library tests completed successfully.\00"
@.str.5 = private unnamed_addr constant [4 x i8] c"%s\0A\00"

define i64 @memory_alloc(i64 %size.arg) {
entry:
  %size = alloca i64
  store i64 %size.arg, ptr %size
  %t1 = load i64, ptr %size
  %t2 = call i64 @malloc(i64 %t1)
  ret i64 %t2
}

define void @memory_dealloc(i64 %ptr.arg) {
entry:
  %ptr = alloca i64
  store i64 %ptr.arg, ptr %ptr
  %t1 = load i64, ptr %ptr
  %t2 = call i64 @free(i64 %t1)
  ret void
}

define void @memory_copy(i64 %dest.arg, i64 %src.arg, i64 %n.arg) {
entry:
  %dest = alloca i64
  store i64 %dest.arg, ptr %dest
  %src = alloca i64
  store i64 %src.arg, ptr %src
  %n = alloca i64
  store i64 %n.arg, ptr %n
  %t1 = load i64, ptr %dest
  %t2 = load i64, ptr %src
  %t3 = load i64, ptr %n
  %t4 = call i64 @memcpy(i64 %t1, i64 %t2, i64 %t3)
  ret void
}

define i64 @string_len(ptr %s.arg) {
entry:
  %s = alloca ptr
  store ptr %s.arg, ptr %s
  %t1 = load ptr, ptr %s
  %t2 = call i64 @strlen(ptr %t1)
  ret i64 %t2
}

define i64 @string_compare(ptr %s1.arg, ptr %s2.arg) {
entry:
  %s1 = alloca ptr
  store ptr %s1.arg, ptr %s1
  %s2 = alloca ptr
  store ptr %s2.arg, ptr %s2
  %t1 = load ptr, ptr %s1
  %t2 = load ptr, ptr %s2
  %t3 = call i64 @strcmp(ptr %t1, ptr %t2)
  ret i64 %t3
}

define i64 @fs_open(ptr %filename.arg, ptr %mode.arg) {
entry:
  %filename = alloca ptr
  store ptr %filename.arg, ptr %filename
  %mode = alloca ptr
  store ptr %mode.arg, ptr %mode
  %t1 = load ptr, ptr %filename
  %t2 = load ptr, ptr %mode
  %t3 = call i64 @fopen(ptr %t1, ptr %t2)
  ret i64 %t3
}

define void @fs_close(i64 %fileptr.arg) {
entry:
  %fileptr = alloca i64
  store i64 %fileptr.arg, ptr %fileptr
  %t1 = load i64, ptr %fileptr
  %t2 = call i64 @fclose(i64 %t1)
  ret void
}

define i64 @fs_read(i64 %ptr.arg, i64 %size.arg, i64 %nmemb.arg, i64 %fileptr.arg) {
entry:
  %ptr = alloca i64
  store i64 %ptr.arg, ptr %ptr
  %size = alloca i64
  store i64 %size.arg, ptr %size
  %nmemb = alloca i64
  store i64 %nmemb.arg, ptr %nmemb
  %fileptr = alloca i64
  store i64 %fileptr.arg, ptr %fileptr
  %t1 = load i64, ptr %ptr
  %t2 = load i64, ptr %size
  %t3 = load i64, ptr %nmemb
  %t4 = load i64, ptr %fileptr
  %t5 = call i64 @fread(i64 %t1, i64 %t2, i64 %t3, i64 %t4)
  ret i64 %t5
}

define i64 @fs_write(i64 %ptr.arg, i64 %size.arg, i64 %nmemb.arg, i64 %fileptr.arg) {
entry:
  %ptr = alloca i64
  store i64 %ptr.arg, ptr %ptr
  %size = alloca i64
  store i64 %size.arg, ptr %size
  %nmemb = alloca i64
  store i64 %nmemb.arg, ptr %nmemb
  %fileptr = alloca i64
  store i64 %fileptr.arg, ptr %fileptr
  %t1 = load i64, ptr %ptr
  %t2 = load i64, ptr %size
  %t3 = load i64, ptr %nmemb
  %t4 = load i64, ptr %fileptr
  %t5 = call i64 @fwrite(i64 %t1, i64 %t2, i64 %t3, i64 %t4)
  ret i64 %t5
}

define i64 @net_create_socket(i64 %domain.arg, i64 %type.arg, i64 %protocol.arg) {
entry:
  %domain = alloca i64
  store i64 %domain.arg, ptr %domain
  %type = alloca i64
  store i64 %type.arg, ptr %type
  %protocol = alloca i64
  store i64 %protocol.arg, ptr %protocol
  %t1 = load i64, ptr %domain
  %t2 = load i64, ptr %type
  %t3 = load i64, ptr %protocol
  %t4 = call i64 @socket(i64 %t1, i64 %t2, i64 %t3)
  ret i64 %t4
}

define i64 @net_connect_socket(i64 %sockfd.arg, i64 %addr.arg, i64 %addrlen.arg) {
entry:
  %sockfd = alloca i64
  store i64 %sockfd.arg, ptr %sockfd
  %addr = alloca i64
  store i64 %addr.arg, ptr %addr
  %addrlen = alloca i64
  store i64 %addrlen.arg, ptr %addrlen
  %t1 = load i64, ptr %sockfd
  %t2 = load i64, ptr %addr
  %t3 = load i64, ptr %addrlen
  %t4 = call i64 @connect(i64 %t1, i64 %t2, i64 %t3)
  ret i64 %t4
}

define i64 @net_send_data(i64 %sockfd.arg, i64 %buf.arg, i64 %len.arg, i64 %flags.arg) {
entry:
  %sockfd = alloca i64
  store i64 %sockfd.arg, ptr %sockfd
  %buf = alloca i64
  store i64 %buf.arg, ptr %buf
  %len = alloca i64
  store i64 %len.arg, ptr %len
  %flags = alloca i64
  store i64 %flags.arg, ptr %flags
  %t1 = load i64, ptr %sockfd
  %t2 = load i64, ptr %buf
  %t3 = load i64, ptr %len
  %t4 = load i64, ptr %flags
  %t5 = call i64 @send(i64 %t1, i64 %t2, i64 %t3, i64 %t4)
  ret i64 %t5
}

define i64 @net_receive_data(i64 %sockfd.arg, i64 %buf.arg, i64 %len.arg, i64 %flags.arg) {
entry:
  %sockfd = alloca i64
  store i64 %sockfd.arg, ptr %sockfd
  %buf = alloca i64
  store i64 %buf.arg, ptr %buf
  %len = alloca i64
  store i64 %len.arg, ptr %len
  %flags = alloca i64
  store i64 %flags.arg, ptr %flags
  %t1 = load i64, ptr %sockfd
  %t2 = load i64, ptr %buf
  %t3 = load i64, ptr %len
  %t4 = load i64, ptr %flags
  %t5 = call i64 @recv(i64 %t1, i64 %t2, i64 %t3, i64 %t4)
  ret i64 %t5
}

define i64 @time_now() {
entry:
  %t1 = call i64 @time(i64 0)
  ret i64 %t1
}

define void @main() {
entry:
  %gc_stack_top = alloca i32
  call void @whale_gc_init(ptr %gc_stack_top)
  %t1 = getelementptr inbounds [48 x i8], ptr @.str.0, i64 0, i64 0
  %msg = alloca i64
  store ptr %t1, ptr %msg
  %t2 = load i64, ptr %msg
  %t3 = call i64 @string_len(i64 %t2)
  %length = alloca i64
  store i64 %t3, ptr %length
  %t4 = load i64, ptr %length
  %t5 = getelementptr inbounds [5 x i8], ptr @.str.1, i64 0, i64 0
  %t6 = call i32 (ptr, ...) @printf(ptr %t5, i64 %t4)
  %t9 = call i64 @memory_alloc(i64 %t8)
  %ptr = alloca i64
  store i64 %t9, ptr %ptr
  %t10 = load i64, ptr %ptr
  %t11 = icmp ne i64 %t10, 0
  br i1 %t11, label %if.then.1, label %if.merge.3
if.then.1:
  %t12 = load i64, ptr %ptr
  %t13 = getelementptr inbounds [5 x i8], ptr @.str.1, i64 0, i64 0
  %t14 = call i32 (ptr, ...) @printf(ptr %t13, i64 %t12)
  %t15 = load i64, ptr %ptr
  %t16 = call i64 @memory_dealloc(i64 %t15)
  br label %if.merge.3
if.merge.3:
  %t17 = getelementptr inbounds [16 x i8], ptr @.str.2, i64 0, i64 0
  %t18 = getelementptr inbounds [2 x i8], ptr @.str.3, i64 0, i64 0
  %t19 = call i64 @fs_open(ptr %t17, ptr %t18)
  %file = alloca i64
  store i64 %t19, ptr %file
  %t20 = load i64, ptr %file
  %t21 = icmp ne i64 %t20, 0
  br i1 %t21, label %if.then.4, label %if.merge.6
if.then.4:
  %t22 = load i64, ptr %file
  %t23 = getelementptr inbounds [5 x i8], ptr @.str.1, i64 0, i64 0
  %t24 = call i32 (ptr, ...) @printf(ptr %t23, i64 %t22)
  %t25 = load i64, ptr %file
  %t26 = call i64 @fs_close(i64 %t25)
  br label %if.merge.6
if.merge.6:
  %t27 = call i64 @time_now()
  %current_time = alloca i64
  store i64 %t27, ptr %current_time
  %t28 = load i64, ptr %current_time
  %t29 = getelementptr inbounds [5 x i8], ptr @.str.1, i64 0, i64 0
  %t30 = call i32 (ptr, ...) @printf(ptr %t29, i64 %t28)
  %t31 = call i64 @net_create_socket(i64 2, i64 1, i64 6)
  %sockfd = alloca i64
  store i64 %t31, ptr %sockfd
  %t32 = load i64, ptr %sockfd
  %t33 = icmp ne i64 %t32, 0
  br i1 %t33, label %if.then.7, label %if.merge.9
if.then.7:
  %t34 = load i64, ptr %sockfd
  %t35 = getelementptr inbounds [5 x i8], ptr @.str.1, i64 0, i64 0
  %t36 = call i32 (ptr, ...) @printf(ptr %t35, i64 %t34)
  br label %if.merge.9
if.merge.9:
  %t37 = getelementptr inbounds [47 x i8], ptr @.str.4, i64 0, i64 0
  %t38 = getelementptr inbounds [4 x i8], ptr @.str.5, i64 0, i64 0
  %t39 = call i32 (ptr, ...) @printf(ptr %t38, ptr %t37)
  ret void
}

