; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare void @whale_gc_init(ptr)

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [27 x i8] c"SIMD Compiled successfully\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"%s\0A\00"

define <4 x i64> @test_simd(<4 x i64> %a.arg, <4 x i64> %b.arg) {
entry:
  %a = alloca <4 x i64>
  store <4 x i64> %a.arg, ptr %a
  %b = alloca <4 x i64>
  store <4 x i64> %b.arg, ptr %b
  %t1 = load <4 x i64>, ptr %a
  %t2 = load <4 x i64>, ptr %b
  %t3 = add <4 x i64> %t1, %t2
  ret <4 x i64> %t3
}

define void @main() {
entry:
  %gc_stack_top = alloca i32
  call void @whale_gc_init(ptr %gc_stack_top)
  %t1 = getelementptr inbounds [27 x i8], ptr @.str.0, i64 0, i64 0
  %t2 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t3 = call i32 (ptr, ...) @printf(ptr %t2, ptr %t1)
  ret void
}

