; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

define i64 @test_volatile() {
entry:
  %t1 = bitcast i64 753664 to ptr
  %ptr = alloca i64
  store ptr %t1, ptr %ptr
  %t2 = load i64, ptr %ptr
  %t3 = trunc i64 1857 to i16
  store i16 %t3, ptr %t2
  %t6 = bitcast i64 %t5 to i64
  ret i64 %t6
}

define i64 @test_bitwise(i64 %a.arg, i64 %b.arg) {
entry:
  %a = alloca i64
  store i64 %a.arg, ptr %a
  %b = alloca i64
  store i64 %b.arg, ptr %b
  %t1 = load i64, ptr %a
  %t2 = load i64, ptr %b
  %t3 = or i64 %t1, %t2
  %or_res = alloca i64
  store i64 %t3, ptr %or_res
  %t4 = load i64, ptr %a
  %t5 = load i64, ptr %b
  %t6 = and i64 %t4, %t5
  %and_res = alloca i64
  store i64 %t6, ptr %and_res
  %t7 = load i64, ptr %a
  %t8 = load i64, ptr %b
  %t9 = xor i64 %t7, %t8
  %xor_res = alloca i64
  store i64 %t9, ptr %xor_res
  %t10 = load i64, ptr %a
  %t11 = xor i64 %t10, -1
  %not_res = alloca i64
  store i64 %t11, ptr %not_res
  %t12 = load i64, ptr %a
  %t13 = shl i64 %t12, 2
  %shl_res = alloca i64
  store i64 %t13, ptr %shl_res
  %t14 = load i64, ptr %b
  %t15 = ashr i64 %t14, 1
  %shr_res = alloca i64
  store i64 %t15, ptr %shr_res
  %t25 = load i64, ptr %shr_res
  %t26 = add i64 %t24, %t25
  ret i64 %t26
}

define i64 @test_cast(i64 %x.arg) {
entry:
  %x = alloca i64
  store i64 %x.arg, ptr %x
  %t1 = load i64, ptr %x
  %t2 = trunc i64 %t1 to i8
  %small = alloca i64
  store i8 %t2, ptr %small
  %t3 = load i64, ptr %small
  %t4 = bitcast i64 %t3 to i64
  ret i64 %t4
}

define i64 @test_asm() {
entry:
  %t1 = call i32 asm sideeffect "nop", "=r, ~{memory}"()
  ret i64 0
}

define i64 @_start() {
entry:
  %t1 = call i64 @test_bitwise(i64 5, i64 3)
  %t2 = call i64 @test_cast(i64 257)
  %t3 = call i64 @test_volatile()
  %t4 = call i64 @test_asm()
  ret i64 0
}

