; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare void @whale_gc_init(ptr)

declare ptr @whale_malloc(i64)

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [23 x i8] c"Stream First Element: \00"
@.str.1 = private unnamed_addr constant [7 x i8] c"%s%ld\0A\00"
@.str.2 = private unnamed_addr constant [24 x i8] c"Stream Second Element: \00"

define void @main() {
entry:
  %gc_stack_top = alloca i32
  call void @whale_gc_init(ptr %gc_stack_top)
  %t1 = getelementptr %WhaleArray, ptr null, i32 1
  %t2 = ptrtoint ptr %t1 to i64
  %t3 = call ptr @whale_malloc(i64 %t2)
  %t4 = getelementptr inbounds %WhaleArray, ptr %t3, i32 0, i32 0
  store i64 3, ptr %t4
  %t5 = getelementptr i64, ptr null, i32 1
  %t6 = ptrtoint ptr %t5 to i64
  %t7 = mul i64 %t6, 3
  %t8 = call ptr @whale_malloc(i64 %t7)
  %t9 = getelementptr inbounds %WhaleArray, ptr %t3, i32 0, i32 1
  store ptr %t8, ptr %t9
  %t10 = getelementptr inbounds i64, ptr %t8, i64 0
  store i64 1, ptr %t10
  %t11 = getelementptr inbounds i64, ptr %t8, i64 1
  store i64 2, ptr %t11
  %t12 = getelementptr inbounds i64, ptr %t8, i64 2
  store i64 3, ptr %t12
  %_src_result = alloca ptr
  store ptr %t3, ptr %_src_result
  %t13 = load ptr, ptr %_src_result
  %t14 = getelementptr inbounds %WhaleArray, ptr %t13, i32 0, i32 0
  %t15 = load i64, ptr %t14
  %_len_result = alloca i64
  store i64 %t15, ptr %_len_result
  %t16 = load i64, ptr %_len_result
  %t17 = getelementptr %WhaleArray, ptr null, i32 1
  %t18 = ptrtoint ptr %t17 to i64
  %t19 = call ptr @whale_malloc(i64 %t18)
  %t20 = getelementptr inbounds %WhaleArray, ptr %t19, i32 0, i32 0
  store i64 %t16, ptr %t20
  %t21 = getelementptr i64, ptr null, i32 1
  %t22 = ptrtoint ptr %t21 to i64
  %t23 = mul i64 %t22, %t16
  %t24 = call ptr @whale_malloc(i64 %t23)
  %t25 = getelementptr inbounds %WhaleArray, ptr %t19, i32 0, i32 1
  store ptr %t24, ptr %t25
  %result = alloca ptr
  store ptr %t19, ptr %result
  %_i_result = alloca i64
  store i64 0, ptr %_i_result
  %_out_i_result = alloca i64
  store i64 0, ptr %_out_i_result
  br label %while.cond.1

while.cond.1:
  %t26 = load i64, ptr %_i_result
  %t27 = load i64, ptr %_len_result
  %t28 = icmp slt i64 %t26, %t27
  br i1 %t28, label %while.body.2, label %while.end.3

while.body.2:
  %t29 = load ptr, ptr %_src_result
  %t30 = load i64, ptr %_i_result
  %t31 = getelementptr inbounds %WhaleArray, ptr %t29, i32 0, i32 1
  %t32 = load ptr, ptr %t31
  %t33 = getelementptr inbounds i64, ptr %t32, i64 %t30
  %t34 = load i64, ptr %t33
  %_item_result = alloca i64
  store i64 %t34, ptr %_item_result
  %t35 = load i64, ptr %_item_result
  %x = alloca i64
  store i64 %t35, ptr %x
  %t36 = load i64, ptr %x
  %t37 = mul i64 %t36, 10
  %x = alloca i64
  store i64 %t37, ptr %x
  %t38 = load i64, ptr %x
  %t39 = icmp sgt i64 %t38, 15
  br i1 %t39, label %if.then.4, label %if.merge.6
if.then.4:
  %t40 = load ptr, ptr %result
  %t41 = load i64, ptr %_out_i_result
  %t44 = getelementptr inbounds %WhaleArray, ptr %t40, i32 0, i32 1
  %t45 = load ptr, ptr %t44
  %t46 = getelementptr inbounds i64, ptr %t45, i64 %t41
  store i64 %t43, ptr %t46
  store i64 %t48, ptr %_out_i_result
  br label %if.merge.6
if.merge.6:
  store i64 %t50, ptr %_i_result
  br label %while.cond.1

while.end.3:
  %t51 = getelementptr inbounds [23 x i8], ptr @.str.0, i64 0, i64 0
  %t52 = load ptr, ptr %result
  %t53 = getelementptr inbounds %WhaleArray, ptr %t52, i32 0, i32 1
  %t54 = load ptr, ptr %t53
  %t55 = getelementptr inbounds i64, ptr %t54, i64 0
  %t56 = load i64, ptr %t55
  %t57 = getelementptr inbounds [7 x i8], ptr @.str.1, i64 0, i64 0
  %t58 = call i32 (ptr, ...) @printf(ptr %t57, ptr %t51, i64 %t56)
  %t59 = getelementptr inbounds [24 x i8], ptr @.str.2, i64 0, i64 0
  %t60 = load ptr, ptr %result
  %t61 = getelementptr inbounds %WhaleArray, ptr %t60, i32 0, i32 1
  %t62 = load ptr, ptr %t61
  %t63 = getelementptr inbounds i64, ptr %t62, i64 1
  %t64 = load i64, ptr %t63
  %t65 = getelementptr inbounds [7 x i8], ptr @.str.1, i64 0, i64 0
  %t66 = call i32 (ptr, ...) @printf(ptr %t65, ptr %t59, i64 %t64)
  ret void
}

