; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

%enum.Result = type { i32, i64, ptr }
declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [17 x i8] c"division by zero\00"
@.str.1 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"
@.str.2 = private unnamed_addr constant [4 x i8] c"%s\0A\00"

define ptr @divide(i64 %a.arg, i64 %b.arg) {
entry:
  %a = alloca i64
  store i64 %a.arg, ptr %a
  %b = alloca i64
  store i64 %b.arg, ptr %b
  %t1 = load i64, ptr %b
  %t2 = icmp eq i64 %t1, 0
  br i1 %t2, label %if.then.1, label %if.merge.3
if.then.1:
  %t3 = alloca %enum.Result
  %t4 = getelementptr inbounds %enum.Result, ptr %t3, i32 0, i32 0
  store i32 1, ptr %t4
  %t5 = getelementptr inbounds [17 x i8], ptr @.str.0, i64 0, i64 0
  %t6 = getelementptr inbounds %enum.Result, ptr %t3, i32 0, i32 2
  store ptr %t5, ptr %t6
  ret ptr %t3
if.merge.3:
  unreachable
}

define void @test_match(ptr %res.arg) {
entry:
  %res = alloca ptr
  store ptr %res.arg, ptr %res
  %t1 = load ptr, ptr %res
  %t2 = getelementptr inbounds %enum.Result, ptr %t1, i32 0, i32 0
  %t3 = load i32, ptr %t2
  switch i32 %t3, label %match.default.1 [
    i32 0, label %match.arm.Ok.3
    i32 1, label %match.arm.Err.4
  ]

match.default.1:
  unreachable

match.arm.Ok.3:
  %t4 = getelementptr inbounds %enum.Result, ptr %t1, i32 0, i32 1
  %t5 = load i64, ptr %t4
  %t6 = alloca i64
  store i64 %t5, ptr %t6
  br label %match.arm.exit.5

match.arm.exit.5:
  br label %match.end.2

match.arm.Err.4:
  %t10 = getelementptr inbounds %enum.Result, ptr %t1, i32 0, i32 2
  %t11 = load ptr, ptr %t10
  %t12 = alloca ptr
  store ptr %t11, ptr %t12
  br label %match.arm.exit.6

match.arm.exit.6:
  br label %match.end.2

match.end.2:
  %t16 = phi i64 [ %t9, %match.arm.exit.5 ], [ %t15, %match.arm.exit.6 ]
  ret void
}

