; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare i32 @printf(ptr, ...)

declare void @whale_chan_send(ptr, i64)


@.str.0 = private unnamed_addr constant [7 x i8] c"Worker\00"
@.str.1 = private unnamed_addr constant [5 x i8] c"done\00"
@.str.2 = private unnamed_addr constant [9 x i8] c"%s%ld%s\0A\00"

define void @worker(i64 %id.arg, ptr %c.arg) {
entry:
  %id = alloca i64
  store i64 %id.arg, ptr %id
  %c = alloca ptr
  store ptr %c.arg, ptr %c
  %t1 = getelementptr inbounds [7 x i8], ptr @.str.0, i64 0, i64 0
  %t2 = load i64, ptr %id
  %t3 = getelementptr inbounds [5 x i8], ptr @.str.1, i64 0, i64 0
  %t4 = getelementptr inbounds [9 x i8], ptr @.str.2, i64 0, i64 0
  %t5 = call i32 (ptr, ...) @printf(ptr %t4, ptr %t1, i64 %t2, ptr %t3)
  %t6 = load ptr, ptr %c
  %t7 = load i64, ptr %id
  %t8 = mul i64 %t7, 10
  call void @whale_chan_send(ptr %t6, i64 %t8)
  ret void
}

