; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare void @whale_gc_init(ptr)

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [17 x i8] c"res1 (Success): \00"
@.str.1 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"
@.str.3 = private unnamed_addr constant [17 x i8] c"res2 (Failure): \00"

define i64 @might_fail(i1 %fail.arg) {
entry:
  %fail = alloca i1
  store i1 %fail.arg, ptr %fail
  %t1 = load i1, ptr %fail
  br i1 %t1, label %if.then.1, label %if.merge.3
if.then.1:
  ret i64 0
if.merge.3:
  unreachable
}

define i64 @do_something(i1 %fail.arg) {
entry:
  %fail = alloca i1
  store i1 %fail.arg, ptr %fail
  %val = alloca i64
  store i64 %t2, ptr %val
  %t3 = load i64, ptr %val
  %t4 = add i64 %t3, 10
  ret i64 %t4
}

define void @main() {
entry:
  %gc_stack_top = alloca i32
  call void @whale_gc_init(ptr %gc_stack_top)
  %t1 = call i64 @do_something(i1 0)
  %res1 = alloca i64
  store i64 %t1, ptr %res1
  %t2 = getelementptr inbounds [17 x i8], ptr @.str.0, i64 0, i64 0
  %t3 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t4 = call i32 (ptr, ...) @printf(ptr %t3, ptr %t2)
  %t5 = load i64, ptr %res1
  %t6 = getelementptr inbounds [5 x i8], ptr @.str.2, i64 0, i64 0
  %t7 = call i32 (ptr, ...) @printf(ptr %t6, i64 %t5)
  %t8 = call i64 @do_something(i1 1)
  %res2 = alloca i64
  store i64 %t8, ptr %res2
  %t9 = getelementptr inbounds [17 x i8], ptr @.str.3, i64 0, i64 0
  %t10 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t11 = call i32 (ptr, ...) @printf(ptr %t10, ptr %t9)
  %t12 = load i64, ptr %res2
  %t13 = getelementptr inbounds [5 x i8], ptr @.str.2, i64 0, i64 0
  %t14 = call i32 (ptr, ...) @printf(ptr %t13, i64 %t12)
  ret void
}

