; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

%struct.Point = type { i64, i64 }

declare void @whale_gc_init(ptr)

declare ptr @whale_malloc(i64)

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"

define void @main() {
entry:
  %gc_stack_top = alloca i32
  call void @whale_gc_init(ptr %gc_stack_top)
  %t1 = getelementptr %struct.Point, ptr null, i32 1
  %t2 = ptrtoint ptr %t1 to i64
  %t3 = call ptr @whale_malloc(i64 %t2)
  %t4 = getelementptr inbounds %struct.Point, ptr %t3, i32 0, i32 0
  store i64 1, ptr %t4
  %t5 = getelementptr inbounds %struct.Point, ptr %t3, i32 0, i32 1
  store i64 2, ptr %t5
  %p = alloca ptr
  store ptr %t3, ptr %p
  %t6 = load ptr, ptr %p
  %t7 = getelementptr inbounds %struct.Point, ptr %t6, i32 0, i32 0
  store i64 100, ptr %t7
  %t8 = load ptr, ptr %p
  %t9 = getelementptr inbounds %struct.Point, ptr %t8, i32 0, i32 1
  store i64 200, ptr %t9
  %t10 = load ptr, ptr %p
  %t11 = getelementptr inbounds %struct.Point, ptr %t10, i32 0, i32 0
  %t12 = load i64, ptr %t11
  %t13 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t14 = call i32 (ptr, ...) @printf(ptr %t13, i64 %t12)
  %t15 = load ptr, ptr %p
  %t16 = getelementptr inbounds %struct.Point, ptr %t15, i32 0, i32 1
  %t17 = load i64, ptr %t16
  %t18 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t19 = call i32 (ptr, ...) @printf(ptr %t18, i64 %t17)
  %t20 = getelementptr %WhaleArray, ptr null, i32 1
  %t21 = ptrtoint ptr %t20 to i64
  %t22 = call ptr @whale_malloc(i64 %t21)
  %t23 = getelementptr inbounds %WhaleArray, ptr %t22, i32 0, i32 0
  store i64 3, ptr %t23
  %t24 = getelementptr i64, ptr null, i32 1
  %t25 = ptrtoint ptr %t24 to i64
  %t26 = mul i64 %t25, 3
  %t27 = call ptr @whale_malloc(i64 %t26)
  %t28 = getelementptr inbounds %WhaleArray, ptr %t22, i32 0, i32 1
  store ptr %t27, ptr %t28
  %t29 = getelementptr inbounds i64, ptr %t27, i64 0
  store i64 1, ptr %t29
  %t30 = getelementptr inbounds i64, ptr %t27, i64 1
  store i64 2, ptr %t30
  %t31 = getelementptr inbounds i64, ptr %t27, i64 2
  store i64 3, ptr %t31
  %arr = alloca ptr
  store ptr %t22, ptr %arr
  %t32 = load ptr, ptr %arr
  %t33 = getelementptr inbounds %WhaleArray, ptr %t32, i32 0, i32 1
  %t34 = load ptr, ptr %t33
  %t35 = getelementptr inbounds i64, ptr %t34, i64 0
  store i64 99, ptr %t35
  %t36 = load ptr, ptr %arr
  %t37 = getelementptr inbounds %WhaleArray, ptr %t36, i32 0, i32 1
  %t38 = load ptr, ptr %t37
  %t39 = getelementptr inbounds i64, ptr %t38, i64 0
  %t40 = load i64, ptr %t39
  %t41 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t42 = call i32 (ptr, ...) @printf(ptr %t41, i64 %t40)
  ret void
}

