; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit — regenerate from source instead.
; ============================================================

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"

define i64 @add(i64 %a.arg, i64 %b.arg) {
entry:
  %a = alloca i64
  store i64 %a.arg, ptr %a
  %b = alloca i64
  store i64 %b.arg, ptr %b
  %t1 = load i64, ptr %a
  %t2 = load i64, ptr %b
  %t3 = add i64 %t1, %t2
  ret i64 %t3
}

define void @main() {
entry:
  %x = alloca i64
  store i64 10, ptr %x
  %y = alloca i64
  store i64 5, ptr %y
  %t1 = load i64, ptr %x
  %t2 = load i64, ptr %y
  %t3 = icmp sgt i64 %t1, %t2
  br i1 %t3, label %if.then.1, label %if.merge.3
if.then.1:
  %t4 = load i64, ptr %x
  %t5 = load i64, ptr %y
  %t6 = call i64 @add(i64 %t4, i64 %t5)
  %z = alloca i64
  store i64 %t6, ptr %z
  %t7 = load i64, ptr %z
  %t8 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t9 = call i32 (ptr, ...) @printf(ptr %t8, i64 %t7)
  br label %if.merge.3
if.merge.3:
  ret void
}

