; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare ptr @malloc(i64)

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"

define void @main() {
entry:
  %t1 = getelementptr %WhaleArray, ptr null, i32 1
  %t2 = ptrtoint ptr %t1 to i64
  %t3 = call ptr @malloc(i64 %t2)
  %t4 = getelementptr inbounds %WhaleArray, ptr %t3, i32 0, i32 0
  store i64 3, ptr %t4
  %t5 = getelementptr i64, ptr null, i32 1
  %t6 = ptrtoint ptr %t5 to i64
  %t7 = mul i64 %t6, 3
  %t8 = call ptr @malloc(i64 %t7)
  %t9 = getelementptr inbounds %WhaleArray, ptr %t3, i32 0, i32 1
  store ptr %t8, ptr %t9
  %t10 = getelementptr inbounds i64, ptr %t8, i64 0
  store i64 10, ptr %t10
  %t11 = getelementptr inbounds i64, ptr %t8, i64 1
  store i64 20, ptr %t11
  %t12 = getelementptr inbounds i64, ptr %t8, i64 2
  store i64 30, ptr %t12
  %_src_arr = alloca ptr
  store ptr %t3, ptr %_src_arr
  %t13 = load ptr, ptr %_src_arr
  %t14 = getelementptr inbounds %WhaleArray, ptr %t13, i32 0, i32 0
  %t15 = load i64, ptr %t14
  %_len_arr = alloca i64
  store i64 %t15, ptr %_len_arr
  %t16 = load i64, ptr %_len_arr
  %t17 = getelementptr %WhaleArray, ptr null, i32 1
  %t18 = ptrtoint ptr %t17 to i64
  %t19 = call ptr @malloc(i64 %t18)
  %t20 = getelementptr inbounds %WhaleArray, ptr %t19, i32 0, i32 0
  store i64 %t16, ptr %t20
  %t21 = getelementptr i64, ptr null, i32 1
  %t22 = ptrtoint ptr %t21 to i64
  %t23 = mul i64 %t22, %t16
  %t24 = call ptr @malloc(i64 %t23)
  %t25 = getelementptr inbounds %WhaleArray, ptr %t19, i32 0, i32 1
  store ptr %t24, ptr %t25
  %arr = alloca ptr
  store ptr %t19, ptr %arr
  %_i_arr = alloca i64
  store i64 0, ptr %_i_arr
  %_out_i_arr = alloca i64
  store i64 0, ptr %_out_i_arr
  br label %while.cond.1

while.cond.1:
  %t26 = load i64, ptr %_i_arr
  %t27 = load i64, ptr %_len_arr
  %t28 = icmp slt i64 %t26, %t27
  br i1 %t28, label %while.body.2, label %while.end.3

while.body.2:
  %t29 = load ptr, ptr %_src_arr
  %t30 = load i64, ptr %_i_arr
  %t31 = getelementptr inbounds %WhaleArray, ptr %t29, i32 0, i32 1
  %t32 = load ptr, ptr %t31
  %t33 = getelementptr inbounds i64, ptr %t32, i64 %t30
  %t34 = load i64, ptr %t33
  %_item_arr = alloca i64
  store i64 %t34, ptr %_item_arr
  %t35 = load i64, ptr %_item_arr
  %x = alloca i64
  store i64 %t35, ptr %x
  %t36 = load ptr, ptr %arr
  %t37 = load i64, ptr %_out_i_arr
  %t40 = getelementptr inbounds %WhaleArray, ptr %t36, i32 0, i32 1
  %t41 = load ptr, ptr %t40
  %t42 = getelementptr inbounds i64, ptr %t41, i64 %t37
  store i64 %t39, ptr %t42
  store i64 %t44, ptr %_out_i_arr
  store i64 %t46, ptr %_i_arr
  br label %while.cond.1

while.end.3:
  %t47 = load ptr, ptr %arr
  %t48 = getelementptr inbounds %WhaleArray, ptr %t47, i32 0, i32 1
  %t49 = load ptr, ptr %t48
  %t50 = getelementptr inbounds i64, ptr %t49, i64 0
  %t51 = load i64, ptr %t50
  %t52 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t53 = call i32 (ptr, ...) @printf(ptr %t52, i64 %t51)
  %t54 = load ptr, ptr %arr
  %t55 = getelementptr inbounds %WhaleArray, ptr %t54, i32 0, i32 1
  %t56 = load ptr, ptr %t55
  %t57 = getelementptr inbounds i64, ptr %t56, i64 1
  %t58 = load i64, ptr %t57
  %t59 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t60 = call i32 (ptr, ...) @printf(ptr %t59, i64 %t58)
  %t61 = load ptr, ptr %arr
  %t62 = getelementptr inbounds %WhaleArray, ptr %t61, i32 0, i32 1
  %t63 = load ptr, ptr %t62
  %t64 = getelementptr inbounds i64, ptr %t63, i64 2
  %t65 = load i64, ptr %t64
  %t66 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t67 = call i32 (ptr, ...) @printf(ptr %t66, i64 %t65)
  ret void
}

