; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare ptr @malloc(i64)

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"

define void @main() {
entry:
  %t1 = getelementptr %WhaleArray, ptr null, i32 1
  %t2 = ptrtoint ptr %t1 to i64
  %t3 = call ptr @malloc(i64 %t2)
  %t4 = getelementptr inbounds %WhaleArray, ptr %t3, i32 0, i32 0
  store i64 3, ptr %t4
  %t5 = getelementptr i64, ptr null, i32 1
  %t6 = ptrtoint ptr %t5 to i64
  %t7 = mul i64 %t6, 3
  %t8 = call ptr @malloc(i64 %t7)
  %t9 = getelementptr inbounds %WhaleArray, ptr %t3, i32 0, i32 1
  store ptr %t8, ptr %t9
  %t10 = getelementptr inbounds i64, ptr %t8, i64 0
  store i64 10, ptr %t10
  %t11 = getelementptr inbounds i64, ptr %t8, i64 1
  store i64 20, ptr %t11
  %t12 = getelementptr inbounds i64, ptr %t8, i64 2
  store i64 30, ptr %t12
  %arr = alloca ptr
  store ptr %t3, ptr %arr
  %t13 = load ptr, ptr %arr
  %t14 = getelementptr inbounds %WhaleArray, ptr %t13, i32 0, i32 1
  %t15 = load ptr, ptr %t14
  %t16 = getelementptr inbounds i64, ptr %t15, i64 0
  %t17 = load i64, ptr %t16
  %t18 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t19 = call i32 (ptr, ...) @printf(ptr %t18, i64 %t17)
  %t20 = load ptr, ptr %arr
  %t21 = getelementptr inbounds %WhaleArray, ptr %t20, i32 0, i32 1
  %t22 = load ptr, ptr %t21
  %t23 = getelementptr inbounds i64, ptr %t22, i64 1
  %t24 = load i64, ptr %t23
  %t25 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t26 = call i32 (ptr, ...) @printf(ptr %t25, i64 %t24)
  %t27 = load ptr, ptr %arr
  %t28 = getelementptr inbounds %WhaleArray, ptr %t27, i32 0, i32 1
  %t29 = load ptr, ptr %t28
  %t30 = getelementptr inbounds i64, ptr %t29, i64 2
  %t31 = load i64, ptr %t30
  %t32 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t33 = call i32 (ptr, ...) @printf(ptr %t32, i64 %t31)
  ret void
}

