; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%struct.Point = type { i64, i64 }

declare ptr @malloc(i64)

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"

define void @main() {
entry:
  %t1 = getelementptr %struct.Point, ptr null, i32 1
  %t2 = ptrtoint ptr %t1 to i64
  %t3 = call ptr @malloc(i64 %t2)
  %t4 = getelementptr inbounds %struct.Point, ptr %t3, i32 0, i32 0
  store i64 10, ptr %t4
  %t5 = getelementptr inbounds %struct.Point, ptr %t3, i32 0, i32 1
  store i64 20, ptr %t5
  %p = alloca ptr
  store ptr %t3, ptr %p
  %t6 = load ptr, ptr %p
  %t7 = getelementptr inbounds %struct.Point, ptr %t6, i32 0, i32 0
  %t8 = load i64, ptr %t7
  %t9 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t10 = call i32 (ptr, ...) @printf(ptr %t9, i64 %t8)
  %t11 = load ptr, ptr %p
  %t12 = getelementptr inbounds %struct.Point, ptr %t11, i32 0, i32 1
  %t13 = load i64, ptr %t12
  %t14 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t15 = call i32 (ptr, ...) @printf(ptr %t14, i64 %t13)
  ret void
}

