; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare i32 @printf(ptr, ...)


@.str.0 = private unnamed_addr constant [12 x i8] c"hello world\00"
@.str.1 = private unnamed_addr constant [6 x i8] c"x is \00"
@.str.2 = private unnamed_addr constant [7 x i8] c"%s%ld\0A\00"
@.str.3 = private unnamed_addr constant [9 x i8] c"text is \00"

define void @main() {
entry:
  %x = alloca i64
  store i64 10, ptr %x
  %t1 = getelementptr inbounds [12 x i8], ptr @.str.0, i64 0, i64 0
  %text = alloca i64
  store ptr %t1, ptr %text
  %t2 = getelementptr inbounds [6 x i8], ptr @.str.1, i64 0, i64 0
  %t3 = load i64, ptr %x
  %t4 = getelementptr inbounds [7 x i8], ptr @.str.2, i64 0, i64 0
  %t5 = call i32 (ptr, ...) @printf(ptr %t4, ptr %t2, i64 %t3)
  %t6 = getelementptr inbounds [9 x i8], ptr @.str.3, i64 0, i64 0
  %t7 = load i64, ptr %text
  %t8 = getelementptr inbounds [7 x i8], ptr @.str.2, i64 0, i64 0
  %t9 = call i32 (ptr, ...) @printf(ptr %t8, ptr %t6, i64 %t7)
  ret void
}

