; ============================================================
; Generated by the Whale native codegen backend (Phase 7)
; Do not hand-edit ? regenerate from source instead.
; ============================================================

%WhaleArray = type { i64, ptr }

declare i32 @printf(ptr, ...)

declare void @whale_write_file(ptr, ptr)

declare ptr @whale_read_file(ptr)


@.str.0 = private unnamed_addr constant [26 x i8] c"Testing string functions:\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.2 = private unnamed_addr constant [12 x i8] c"Hello Whale\00"
@.str.3 = private unnamed_addr constant [11 x i8] c"Original: \00"
@.str.4 = private unnamed_addr constant [8 x i8] c"Lower: \00"
@.str.5 = private unnamed_addr constant [8 x i8] c"Upper: \00"
@.str.6 = private unnamed_addr constant [24 x i8] c"Testing math functions:\00"
@.str.7 = private unnamed_addr constant [6 x i8] c"Abs: \00"
@.str.8 = private unnamed_addr constant [6 x i8] c"Max: \00"
@.str.9 = private unnamed_addr constant [17 x i8] c"Testing file IO:\00"
@.str.10 = private unnamed_addr constant [9 x i8] c"test.txt\00"
@.str.11 = private unnamed_addr constant [18 x i8] c"line1\0Aline2\0Aline3\00"
@.str.12 = private unnamed_addr constant [15 x i8] c"File Content: \00"

define void @main() {
entry:
  %t2 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t3 = call i32 (ptr, ...) @printf(ptr %t2, ptr %t1)
  %t4 = getelementptr inbounds [12 x i8], ptr @.str.2, i64 0, i64 0
  %text = alloca i64
  store ptr %t4, ptr %text
  %t6 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t7 = call i32 (ptr, ...) @printf(ptr %t6, ptr %t5)
  %t9 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t10 = call i32 (ptr, ...) @printf(ptr %t9, ptr %t8)
  %t12 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t13 = call i32 (ptr, ...) @printf(ptr %t12, ptr %t11)
  %t15 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t16 = call i32 (ptr, ...) @printf(ptr %t15, ptr %t14)
  %t17 = fsub double 0.000000, 42.500000
  %num = alloca double
  store double %t17, ptr %num
  %t19 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t20 = call i32 (ptr, ...) @printf(ptr %t19, ptr %t18)
  %t22 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t23 = call i32 (ptr, ...) @printf(ptr %t22, ptr %t21)
  %t25 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t26 = call i32 (ptr, ...) @printf(ptr %t25, ptr %t24)
  %t29 = call void @whale_write_file(ptr %t27, ptr %t28)
  %t31 = call ptr @whale_read_file(ptr %t30)
  %content = alloca i64
  store ptr %t31, ptr %content
  %t33 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %t34 = call i32 (ptr, ...) @printf(ptr %t33, ptr %t32)
  ret void
}

